headless: true
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/115 Safari/537.36"

suppliers:
  - supplier: "Castorama"
    base_url: "https://www.castorama.fr"
    categories:
      - name: "All Products"
        url: "https://www.castorama.fr"  
        selectors:
          card: "[data-test-id='product-tile']"
        paging:
          mode: "pagination"
          next_button: "a[rel='next']"
          max_pages: 15

  - supplier: "Leroy Merlin"
    base_url: "https://www.leroymerlin.fr"
    categories:
      - name: "All Products"
        url: "https://www.leroymerlin.fr"
        selectors:
          card: "li.product-thumbnail"
        paging:
          mode: "pagination"
          next_button: ".a-pagination__link[rel='next']"
          max_pages: 10

  - supplier: "ManoMano"
    base_url: "https://www.manomano.fr"
    categories:
      - name: "All Products"
        url: "https://www.manomano.fr/recherche/produits"
        selectors:
          card: "a[data-testid='productCardListing']"
        paging:
          mode: "infinite_scroll"
          scroll_steps: 1
          scroll_wait_ms: 400
